class RunFailedException(Exception):
    pass


class RunPendingException(Exception):
    pass
